# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 03:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160705_2230'),
        ('blog', '0004_auto_20160705_2316'),
    ]

    operations = [
    ]
